name: krk_stops_app
description: KrkStops application

publish_to: 'none'

version: 1.14.4+31

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  protobuf: ^2.0.0
  grpc: ^3.0.0
  shared_preferences: ^2.0.3
  geolocator: ^9.0.0
  url_launcher: ^6.0.2
  google_sign_in: ^6.1.0
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  protoc_plugin: ^20.0.0
  flutter_launcher_icons: ^0.13.0

flutter:

  uses-material-design: true

  assets:
    - images/airly.png

  generate: true

flutter_icons:
  android: trues
  image_path: "images/icon.png"
  adaptive_icon_background: "#CBCBCB"
  adaptive_icon_foreground: "images/icon.png"
  min_sdk_android: 21