name: krk_stops_app
description: KrkStops application

publish_to: 'none'

version: 1.3.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.0
  grpc: ^3.0.0
  shared_preferences: ^2.0.3
  flutter_material_color_picker: ^1.0.5
  geolocator: ^7.0.1
  url_launcher: ^6.0.2
  google_sign_in: ^5.0.0
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  firebase_crashlytics: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/airly.png

