name: krk_stops_app
description: KrkStops application

publish_to: 'none'

version: 1.10.0+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  protobuf: ^2.0.0
  grpc: ^3.0.0
  shared_preferences: ^2.0.3
  geolocator: ^7.0.1
  url_launcher: ^6.0.2
  google_sign_in: ^5.0.0
  firebase_core: ^1.0.0
  firebase_auth: ^3.0.0
  cloud_firestore: ^2.2.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/airly.png

  generate: true

